name: "Phase 1 - Authentication Task"
description: "Create a new Phase 1 authentication-related task"
title: "[Phase 1] [Auth] "
labels: ["phase-1", "enhancement", "authentication"]
body:
  - type: input
    id: task-name
    attributes:
      label: "Authentication Task Name"
      description: "Brief description of the authentication task"
      placeholder: "e.g., Setup User Registration System"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Clear, testable criteria that define when this authentication task is complete"
      placeholder: |
        - [ ] User can register with email and password
        - [ ] Password meets security requirements
        - [ ] User receives email confirmation
        - [ ] Authentication tokens are properly managed
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List which other issues must be completed before this authentication task can be started"
      placeholder: |
        - Issue #X: Database setup
        - Issue #Y: Email service configuration
        
        Or write "None" if no dependencies exist.

  - type: textarea
    id: technical-requirements
    attributes:
      label: "Technical Requirements"
      description: "Authentication-specific technical implementation details"
      placeholder: |
        - Authentication strategy (Devise, custom, etc.)
        - Password hashing algorithm
        - Session management approach
        - Token storage and security
        - Password reset functionality
        - Account lockout policies
    validations:
      required: true

  - type: textarea
    id: security-considerations
    attributes:
      label: "Security Considerations"
      description: "Security requirements specific to authentication"
      placeholder: |
        - Password complexity requirements
        - Rate limiting for login attempts
        - Secure password reset flow
        - Protection against brute force attacks
        - Session security and timeout
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: "Testing Requirements"
      description: "Authentication-specific testing scenarios"
      placeholder: |
        - Unit tests for authentication models
        - Integration tests for login/logout flows
        - Security tests for attack scenarios
        - End-to-end tests for complete user journey
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Additional Notes"
      description: "Any other authentication-related information or considerations"
      placeholder: "Optional: Add any additional context or notes..."