name: "Phase 1 - Messaging Task"
description: "Create a new Phase 1 messaging-related task"
title: "[Phase 1] [Messaging] "
labels: ["phase-1", "enhancement", "messaging"]
body:
  - type: input
    id: task-name
    attributes:
      label: "Messaging Task Name"
      description: "Brief description of the messaging task"
      placeholder: "e.g., Setup Real-time Chat System"
    validations:
      required: true

  - type: dropdown
    id: messaging-type
    attributes:
      label: "Messaging Feature Type"
      description: "Select the type of messaging functionality"
      options:
        - Real-time Chat
        - Direct Messages
        - Group Messaging
        - Push Notifications
        - Email Notifications
        - SMS Integration
        - Message Broadcasting
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Clear, testable criteria that define when this messaging task is complete"
      placeholder: |
        - [ ] Users can send and receive messages
        - [ ] Real-time delivery is working
        - [ ] Message history is preserved
        - [ ] Message status (sent/delivered/read) tracking
        - [ ] Proper error handling for failed messages
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List which other issues must be completed before this messaging task can be started"
      placeholder: |
        - Issue #X: User authentication system
        - Issue #Y: WebSocket infrastructure
        
        Or write "None" if no dependencies exist.

  - type: textarea
    id: technical-requirements
    attributes:
      label: "Technical Requirements"
      description: "Messaging-specific technical implementation details"
      placeholder: |
        - Real-time transport (WebSockets, Action Cable, etc.)
        - Message queue system
        - Database schema for messages
        - Push notification service integration
        - Message encryption/security
        - Rate limiting and spam prevention
    validations:
      required: true

  - type: textarea
    id: data-requirements
    attributes:
      label: "Data Requirements"
      description: "Message data structure and storage needs"
      placeholder: |
        - Message content storage and indexing
        - Conversation/thread organization
        - Message metadata (timestamps, status, etc.)
        - File attachment handling
        - Message retention policies
        - Search functionality requirements
    validations:
      required: true

  - type: textarea
    id: real-time-requirements
    attributes:
      label: "Real-time Requirements"
      description: "Requirements for real-time messaging functionality"
      placeholder: |
        - Message delivery latency requirements
        - Connection handling and reconnection
        - Offline message queuing
        - Presence indicators (online/typing status)
        - Scalability for concurrent users
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: "Testing Requirements"
      description: "Messaging-specific testing scenarios"
      placeholder: |
        - Real-time message delivery tests
        - Connection failure and recovery tests
        - Load testing for concurrent messaging
        - Message persistence and retrieval tests
        - Cross-browser/device compatibility tests
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Additional Notes"
      description: "Any other messaging-related information or considerations"
      placeholder: "Optional: Add any additional context or notes..."