name: "Phase 1 - OAuth Task"
description: "Create a new Phase 1 OAuth-related task"
title: "[Phase 1] [OAuth] "
labels: ["phase-1", "enhancement", "oauth"]
body:
  - type: input
    id: task-name
    attributes:
      label: "OAuth Task Name"
      description: "Brief description of the OAuth task"
      placeholder: "e.g., Setup Google OAuth Integration"
    validations:
      required: true

  - type: dropdown
    id: oauth-provider
    attributes:
      label: "OAuth Provider"
      description: "Select the OAuth provider for this task"
      options:
        - Google
        - GitHub
        - Facebook
        - Twitter/X
        - LinkedIn
        - Microsoft
        - Apple
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Clear, testable criteria that define when this OAuth task is complete"
      placeholder: |
        - [ ] OAuth application registered with provider
        - [ ] OAuth flow properly configured
        - [ ] User can authenticate via OAuth
        - [ ] User data is properly synchronized
        - [ ] Error handling for OAuth failures
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List which other issues must be completed before this OAuth task can be started"
      placeholder: |
        - Issue #X: Basic authentication system
        - Issue #Y: User model setup
        
        Or write "None" if no dependencies exist.

  - type: textarea
    id: technical-requirements
    attributes:
      label: "Technical Requirements"
      description: "OAuth-specific technical implementation details"
      placeholder: |
        - OAuth gem/library to use (omniauth, etc.)
        - Callback URL configuration
        - Scope permissions required
        - User data mapping strategy
        - Token refresh handling
        - Account linking/unlinking logic
    validations:
      required: true

  - type: textarea
    id: configuration-requirements
    attributes:
      label: "Configuration Requirements"
      description: "OAuth provider setup and configuration needs"
      placeholder: |
        - Application registration with provider
        - Client ID and secret management
        - Redirect URI configuration
        - Required permissions/scopes
        - Environment variable setup
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: "Testing Requirements"
      description: "OAuth-specific testing scenarios"
      placeholder: |
        - OAuth flow integration tests
        - User data synchronization tests
        - Error handling tests (failed auth, network issues)
        - Account linking/unlinking tests
        - Mock OAuth provider for testing
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Additional Notes"
      description: "Any other OAuth-related information or considerations"
      placeholder: "Optional: Add any additional context or notes..."