# PostgreSQL configuration for CI/CD environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ragged_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: ragged_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
